#!/usr/bin/env scons

# Simulate data under various different settings and fit models

import os

from os.path import join
from nestly.scons import SConsWrap
from nestly import Nest
import SCons.Script as sc

# Command line options

sc.AddOption('--clusters', type='string', help="Clusters", default='debug')
sc.AddOption('--seeds', type='int', help="SEEDS", default=1)
sc.AddOption('--output', type='string', help="output folder", default='_output')

env = sc.Environment(
        ENV=os.environ,
        clusters=sc.GetOption('clusters'),
        num_seeds=sc.GetOption('seeds'),
        output=sc.GetOption('output'))

sc.Export('env')

env.SConsignFile()

flag = 'simulation_iid'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_adversary'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_ttest'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_drift'
sc.SConscript(flag + '/sconscript', exports=['flag'])

#flag = 'experiment_yelp'
#sc.SConscript(flag + '/sconscript', exports=['flag'])
#
#flag = 'experiment_mimic'
#sc.SConscript(flag + '/sconscript', exports=['flag'])
#
